### ISSUE TITLE
Type Error when calling bem.write_hdf5() on Nemoh Data

### ISSUE THREAD

**Issue by max-lg** [WEC-Sim/bemio#4] opened 2015-04-12 06:32 UTC
Trying to call write_hdf5() write the NemohOutput data generated from the Nemoh tutorial. 

After running \tutorials\nemoh\run.py I try to run the following code. 
```
>>> nem
<bemio.io.nemoh.NemohOutput object at 0x04BE3130>
>>> from bemio.data_structures import bem
>>> bem.write_hdf5(data=nem.data, out_file="test.hdf5")
Traceback (most recent call last):
  File "<pyshell#26>", line 1, in <module>
    bem.write_hdf5(data=nem.data, out_file="test.hdf5")
  File "build\bdist.win32\egg\bemio\data_structures\bem.py", line 519, in write_hdf5
    cg = f.create_dataset('body' + str(key+1) + '/properties/cg',data=data[key].cg)
  File "C:\Python27\lib\site-packages\h5py\_hl\group.py", line 103, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Python27\lib\site-packages\h5py\_hl\dataset.py", line 87, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1448, in h5py.h5t.py_create (c:\hdf5\h5py\h5py\h5t.c:15508)
  File "h5py\h5t.pyx", line 1468, in h5py.h5t.py_create (c:\hdf5\h5py\h5py\h5t.c:15339)
  File "h5py\h5t.pyx", line 1523, in h5py.h5t.py_create (c:\hdf5\h5py\h5py\h5t.c:15257)
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

**Comment by lawsonro3** [comment] 2015-04-13 18:18
Thanks for the bug report - im pretty sure I know what the problem is, and I'll try to get it fixed by tomorrow. if you could post the Nemoh files you are trying to read that would be helpful.

-Mike

**Comment by max-lg** [comment] 2015-04-13 18:29
I ran the unmodified run.py from within the bemio/tutorials/nemoh/
directory from this repository on commit b47a83b71d. Running that code output data to the variable 'nem' and then the results from an interactive python session are in my last comment.

So this was using the tutorial Nemoh files in this repository at bemio/tutorials/nemoh/data/two_body/ 

Thanks so much for looking into this! If there's any other info, logs, or information I can provide you with I'm really happy to help.

**Comment by lawsonro3** [comment] 2015-04-13 18:30
Thats all I needed. Thanks! I'll get back to you soon on this.

**Comment by lawsonro3** [comment] 2015-04-15 02:00
I have fixed this issue and have done some rebasing to clean up the commit history. Please update to the latest version and let me know if you are having any other problems.

I'm closing this issue for now, but I will reopen if needed.

Thanks for reporting the problem!

**Closed by lawsonro3** 2015-04-15 02:00 UTC

**Comment by lawsonro3** [comment] 2015-04-15 03:43
I also updated the tutorial for NEMOH. See here - file:///Users/mlawson/Applications/bemio/doc/build/html/nemoh.html
